### ISSUE TITLE
Reload vuetable when i click button each time

### ISSUE THREAD

**Issue by tuticorinbala** [ratiw/vuetable-2#120]
Hi Ratiw,

I want to reload vuetable, when i click button each time assign new values to "api-url" and reload the vuetable. Is it possoble?

**Comment by cristijora** [comment]
`this.$refs.vuetable.refresh()` assuming you have `<vue-table ref="vuetable"></vue-table>`

**Comment by tuticorinbala** [comment]
Hi Cristi,

Thanks for your response it is reloaded fine, *But how to assign api-url
each time(dynamically) before executing this.$refs.vuetable.refresh()
method*


Regards,
Bala

**Comment by cristijora** [comment]
`<vue-table ref="vuetable" :api-url="myUrl"></vue-table>`

```js
methods: {
  changeUrl(){
   this.myUrl = "new url ..."
   this.$nextTick(()=>{
      this.$refs.vuetable.refresh()
    })
  }
}
```

**Comment by commititup** [comment]
Hi 
I have a situation when server return 404 and table still keeps  loaded data which it's got in  the previous request and don't get updated in case of 404 but get updated if the response is success.
i want to show the Error in table instead of previous request loaded data

//vuetable 
  
```
<vuetable ref="vuetable" v-if="isSubmitted"
                      :api-url= "apiurl"
                      :http-options= "{headers:{'Authorization': 'Basic token'}}"
                      :fields="fields">
</vuetable>
```

//method which get called on each button click

```
showBackupList(){
        this.apiurl= API_LOCATION+"/tools/backupfinder/resources/backups/domains/"+this.domain+"/services/"+this.selectedServices;
        this.isSubmitted = true;
        this.setTableFields(this.selectedServices);
     
    },
```

//selecting different fields for diffrenet input.

```
setTableFields(selectedServices){
      //remove the last element added because of the table fields
      if (this.fields.length > 2){
        this.fields.pop()
      }
      if (selectedServices=='Apache website'){
          this.fields.push('domain');
      }else if (selectedServices == 'MySQL database') {
            this.fields.push('database');
      }
      else if (selectedServices == 'MailStorage'){
        this.fields.push('email');
      }
    }
  },

```
Also fields are not updating it remains whatever it is selected in first response.  
Screenshot : - https://prnt.sc/klyytn
