### ISSUE TITLE
Latest update messing up vue-resource interceptors

### ISSUE THREAD

**Issue by divyanthj** [ratiw/vuetable-2#127]
Just an FYI, the latest ^v1.6.0 doesn't seem to pick up vue-resource interceptors. I had to roll back the vuetable-2 version to v1.3.1 to get it working.

Specifically, I use a vue-resource interceptor to attach an "Authorization" token to HTTP requests. However, it doesn't get added to calls made by vuetable2.

**Comment by ratiw** [comment]
@divyanthj  The latest version is replacing `vue-resource` with `axios`, so you'll have to use the interceptors in `axios` instead. Please see the [release note](https://github.com/ratiw/vuetable-2/releases/tag/v1.6.0)

**Comment by anselmobattisti** [comment]
To solve this problem you need to add in axion interceptos your Authentication 
`import axios from 'axios'
Vue.use(axios)
axios.interceptors.request.use(config => {
  config.headers.Authorization = 'Bearer ' + window.localStorage.getItem('token')
  return config;
})
`

**Comment by ChrisIgel** [comment]
That doesn't work for me sadly. I've defined my interceptors like you did in a separate file and they are working fine, when I use them in my app. But the requests from vuetable2 aren't executed with my defined interceptors.

**Comment by ChrisIgel** [comment]
I have it configured that way and normal axios requests are working but vuetable2 seems to ignore the global axios settings (`axios.defaults` and `axios.interceptors`).

**Comment by chrislandeza** [comment]
Having the same problem as @ChrisIgel 

I already setup the Authorization header on axios config. The authorization header is not being attached if vuetable is the one performing the ajax request.

Has managed to solve this issue?

**Comment by ratiw** [comment]
Can you setup some code in jsfiddle or codepen to demonstrate this problem? And let me know what would you expect from the request and response. I'll see what might be the problem.

**Comment by chrislandeza** [comment]
@ratiw - I think the version mismatch is causing the issue. I tried matching the axios version defined on vuetable-2's package.json which is "`^0.15.3"` and it fixed my problem.

I previously had version `"^0.16.0"`.

**Comment by ozguruysal** [comment]
In case it may help figure out the issue, if I import like:
```
import Vuetable from 'vuetable-2';
```
then Vuetable ignores any global axios settings or intercepters.

Importing it like:
```
import Vuetable from 'vuetable-2/src/components/Vuetable';
```
fixes the issue for me. I'm not sure why we can't import it like in the first example.

**Comment by vincentfuzifeng** [comment]
Hi @ratiw may I know how can I rollback v1.3.1 with dist folder?So that I can directly grab the minified JS file and use it as plugin in my index.html?

**Comment by vincentfuzifeng** [comment]
@ratiw , can you edit your own fiddle http://jsfiddle.net/CristiJ/z11fe07p/1318/ that have the axios example?

**Comment by cristijora** [comment]
@vincentfuzifeng Unfortunately there was no js bundle until version 1.6.0

**Comment by stefanullinger** [comment]
Hi, I currently run into the very same issue – in my project I use a newer version of axios than the one that is used by vuetable-2, so when node imports axios for vuetable-2, it will look into vuetable-2's node_modules directory instead of picking the one in the project's node_modules directory.

I guess the best solution would be that vuetable-2 defines **axios as a peer dependency**. A very good description can be found here: https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins

**Comment by ratiw** [comment]
I actually haven't thought through this issue when switching to `axios`. And there might be more than one solution. The problem is I am not really sure if the solution I would pick would solve all the problem or not.

"Peer dependency" suggested by @stefanullinger is nice but I think it only suggests the user that the version of the axios they're using (probably newer) and the one used by Vuetable as mismatch. 
If they are happy to downgraded to the same version of Vuetable, that would be fine. 

But if they intend to use the newer version because there is/are some features from that version that they need, that will still present a problem.

I'm now leaning toward injecting `axios` to be used inside Vuetable with a fallback. What do you guys think about this solution?

**Comment by stefanullinger** [comment]
I think the short term solution would be to define axios as a peer dependency. I guess axios' API – or at least the parts used by vuetables-2 – are very stable.

The mid or long term solution could be to add an abstraction layer, so you could kind of inject whatever HTTP library you like. This way vuetables-2 would not force you to use axios.

**Comment by lgullestrup** [comment]
Forgive my lack of knowledge on Terminology, i am guessing having Axios as peer dependent would mean that Vuetables would depend on Axios being loaded instead of loading axios itself.

This would certainly allow an application to use a global configuration for axios calls. Custom or specific config requirements would require httpOptions to be set. (you could do this for each table at this stage, how ever i can see how this would be tedious)

If this approach is taken, then it would make sense to add another property (defaulted to false) to tell vuetables to use the default configuration for axios. 

This would allow your to Globally configure Axios, and tell Vuetable to use that global configuration.
any httpOptions set would only overide the options passed into it.

Hope this is making sense?

**Comment by T-Bod** [comment]
Just updated to Axios 16.2 and am running into the same issue, is there a more robust solution than just using 15.3?

**Comment by dehypnosis** [comment]
@ozguruysal thanks god, you saved my time!

**Comment by nusendra** [comment]
```
axios.interceptors.request.use(config => {
  config.headers.Authorization = 'Bearer ' + localStorage.getItem('api_key')
  console.log(config)
  return config;
})
```
this works perfectly.


```
axios.interceptors.response.use(
  function(response) {
    return Promise.resolve(response)
  },
  function(error) {
    console.log(error.response)
    return Promise.reject(error)
  }
)
```
but this is not work. i have other axios request and this code works perfect, but not with vue-table2.
look at this screenshot
![screenshot from 2018-01-08 14-06-54](https://user-images.githubusercontent.com/8466308/34661601-4cec539a-f47d-11e7-8ff9-c2696d56f775.png)

First error is vue-table2 request. when it unauthorized (error), the axios interceptors not working. But take a look the second error. The second error is my other axios request, it unauthorized too, but interceptors is working. 

how to fix this? help me mr. @ratiw
