### ISSUE TITLE
[Question] How to use multiple filter-bar elements on one page?

### ISSUE THREAD

**Issue by andrewnsk** [ratiw/vuetable-2#179]
There was a need to use several filter-bar(search-fields) elements on one page.

My template is:

```
        <input type="text" v-model="filterText" class="three wide column" @keyup.enter="doFilter" placeholder="name">
        <input type="text" v-model="filterText" class="three wide column" @keyup.enter="doFilter" placeholder="house_id">
```

and query string should be:  

`/?name=ExampleName&house_id=ExampleId`

When I add directly to the `moreParams: {}` parameters that I need, this works, but not conveniently.

example:

```
moreParams: {
    name: 'andrew',
    house_id: 'QSDE176'
}
```

Tell me please: how to use several
Instances of vuetable-2 search fields?

**Comment by ratiw** [comment]
@andrewnsk The 'filter-bar' is actually not part of Vuetable-2. It's just there to demonstrate how it could be done. 

Using `v-model="filterText"` on both input are not correct. Since you want to have more than one filter field, the `filterText` should now be an "Object" instead.
```javascript
data () {
  return {
    filterText: {
      name: '',
      house_id: ''
    }
  }
}
```
So, the `input` can be changed to support both filters, like so.
```html
<input type="text" v-model="filterText.name" class="three wide column" placeholder="name">
<input type="text" v-model="filterText.house_id" class="three wide column" placeholder="house_id">
```
The `@keyup` is no longer relevant here because you now have more than one filter, so they are removed in the example above.

Now, the `fileter-set` event will carry the `filterText` object which contains both filter parameter.

All that is left to do is modified `onFilterSet` to send those two filter back to your API. This should do the job.
```javascript
onFilterSet (filterText) {
  this.appendParams.name = filterText.name
  this.appendParams.house_id = filterText.house_id
  Vue.nextTick( () => this.$refs.vuetable.refresh() )
}
```

You may need to adapt the code according to your case anyway.

**Comment by andrewnsk** [comment]
@ratiw Many thanks! :+1: 

Thanks to your help, I figured out,
I'll go to learn Javascript  :smile:
