### ISSUE TITLE
Using from client data, with client-side only filter

### ISSUE THREAD

**Issue by bernhardreiter** [ratiw/vuetable-2#18]
Sometimes it seems to make sense to fully load the table data into the client and work from there.
A client-side only filter could be much faster, just like a switch between table pages.

Are there plans to to develop vuetable-2 in this direction?

Or is it already possible to use client-date and client-side filtering and pagination? If so any hints where to start doing this?

**Comment by ratiw** [comment]
@bernhardreiter There is [this project](https://github.com/ratiw/vueitems) that is already in use in one of my app and it's working pretty well. It serves different purpose than vuetable though, so it works primarily with client-side data. Most of the sorting, filtering functionality were removed anyway.

vuetable was written to serve the a specific need for working with server-side data. Based on my experience, the filterable client-side data table only works for small set of data.  

To answer your question, vuetable-2 is not going to support client-side data filtering because I still don't see the need for it, so I would rather spend time working on some other things. Not that I'm lazy, but I think I really have to much at hands at the moment.

However, if you find vuetable-2 useful and easy to work with, maybe you can fork it and work on the client-side functionality that you want yourself. I think the code is quite easy to understand. And if it works for you, it might work for the others as well. :)

**Comment by bernhardreiter** [comment]
@ratiw thanks for your friendly reply.
I cannot say what I will decide to do, but your suggestions have helped me to understand your current direction with vuetable-2 better. :)
