### ISSUE TITLE
vuetable vs vuetable-2

### ISSUE THREAD

**Issue by vincent-lu** [ratiw/vuetable-2#24]
This is more of a vue vs vue2 question, but we are about to start working on a new project; I'm wondering if we should go with vuetable-2 (and vue2) or vuetable?

@ratiw is it your plan for vuetable-2 to supersede vuetable? Would you recommend using vuetable-2 for production (commercial project that has planned life time of 3~5 years)?

Many thanks and keep up the great work.

**Comment by ratiw** [comment]
@vincent-lu I would recommend you go with Vue 2 since it is a new project and the life span is quite long. Staying with Vue 1.x would make it harder to upgrade or maintain in the long run. So, you'll have to use vuetable-2.

In my opinion, Vue 1.x is still good and solid, but within a year this may change. vuetable will never work in IE, but vuetable-2 does not have this limitation, thanks to Virtual DOM in Vue 2. And in large application, you will have to use vuex to handle state management since event handling is deprecated in Vue 2.

vuetable-2 should supersede vuetable eventually. I will still maintain vuetable for quite sometime as I'm still using it in my project, but it may not have any new feature added. Most of the features in vuetable will be ported to vuetable-2 as soon as I have time to work on it.

**Comment by vincent-lu** [comment]
Yeah I find Vue1 easier to use (and IE isn't a requirement for the new project); but for project longevity sake we should go with Vue2.

The pain point for us now is vuetable-2 doesn't seem to be getting much attention so it is not as safe of a bet as vuetable-1 right now.

Do you happen to have an ETA on when the focus will be on vuetable-2? Anyway I know the answer is probably "it will get worked on when time allows", so thanks for the great work and hope you get the time to jump on vuetable-2 soon.

**Comment by ratiw** [comment]
@vincent-lu Sorry, I really do not have the ETA, but I'll try my best.

**Comment by vincent-lu** [comment]
Not a problem @ratiw totally understand.
