### ISSUE TITLE
Implementation of Frontend Filter

### ISSUE THREAD

**Issue by T0miii** [ratiw/vuetable-2#281]
Hi,

I am trying to implement a frontend filter, using some code from similar issues:

```
            dataManager () {

                let data = this.$refs.vuetable.tableData;

                // account for search filter
                if (this.searchFor) {
                    // the text should be case insensitive
                    let txt = new RegExp(this.searchFor, 'i')

                    data = _.filter(data, function (item) {
                        console.log(item.code.search(txt));
                        return item.code.search(txt) >= 0 || item.internal_name.search(txt) >= 0
                    })
                }

                return {
                    data: data
                }
            }
```
The data variable contains the filtered data:

![image](https://user-images.githubusercontent.com/10532141/31656642-7c91fec0-b32c-11e7-8278-2ef658cda38e.png)

The only thing im not quit sure about how do i set the data now, so the table can display it.
I also tried to set the this.$refs.vuetable.tableData property as the original data is stored there when the AJAX request is done.

EDIT:
i found out that this works at the end of my function. The problem is i have to turn on api mode on every other funcionality.

```
                this.$refs.vuetable.apiMode = false;
                this.$refs.vuetable.data = data;
```

**Comment by ratiw** [comment]
I am not quite sure about your case. It sounds like you are using API mode to retrieve the data and then try to filter those data by switching to Data mode to be able to use Data Manager method to do the filtering, am I right?

**Comment by T0miii** [comment]
Exactly , im getting the data from the server, but i also would like to have a quicksearch filed, where i can type in a word/text and it searches over all columns. for the displayed data.

**Comment by ratiw** [comment]
Well, it was never intended to be used that way since switching back and forth might create unexpected side effect.

And I don't think you need to use the `DataManager` to achieve this functionality since you can use `refs` to access `tableData`, so you could just use the above code inside the click event handler of the search button and it should work the same without having to switch from API to Data mode. 

You can even switch to use Data mode completely and handle the AJAX request yourself via Data Manager method.

Beware that the data you're filtering on the front-end may not be the complete set of the one on the server side.

**Comment by T0miii** [comment]
Your are right, it kinda feels like a mix.
My intention was to create a quick search field like that from jQuery Datatables.
But my actuall sarch is so fast that i think ill just drop the idea completly.
Thx for your suggestions tho.

**Comment by efrenhz2016** [comment]
@T0miii would you shared me your complete code for understant, i'm doing same code...
