### ISSUE TITLE
Refresh a __component from another __component

### ISSUE THREAD

**Issue by kahwooi** [ratiw/vuetable-2#284]
I have a vuetable, that use 2 components: 

```
  import BadgeColumn from './BadgeColumn.vue'
  import CustomActions from './CustomActions.vue'

  Vue.component('badge-column', BadgeColumn)
  Vue.component('custom-actions', CustomActions)
```

How can I refresh BadgeColumn component from CustomActions?

To refresh parent I use `this.$parent.refresh()`, but it won't refresh  BadgeColumn component.

**Comment by ratiw** [comment]
See [this](https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication).

**Comment by kahwooi** [comment]
I did this at BadgeColumn component, the event is successfully emitted but the hook is not call, and how can I refresh the badge column?

   ```
    mounted () {
      this.$on('refresh-badge', () => {
        this.$refs.vuetable.refresh()
      })
    }
```

**Comment by ratiw** [comment]
You need to clearly understand the parent-child communication first.

I think what you did was just setting up the listener (`refresh-badge`) in you BadgeColumn component, but you didn't mention how or where you `emit` the `refresh-badge` event from.

Base on the information you've given, this is what you have at the moment:
```
root Vue instance --> Vuetable --> BadgeColumn, CustomActions
```

If this is the only thing you have, you might use `$root` as a main event bus to emit and listen to the event. Although, it is recommended that you use a dedicate Vue instance to act as a main event bus instead of using `$root`.

With this scenario, you will have to emit to the `$root` like so: `this.$root.emit('refresh-badge')`
and listen to the event like this, `this.$root.$on('refresh-badge')`

For me, I usually use another library called [`vue-events`](https://github.com/cklmercer/vue-events). It easier to understand and use if your app is not so complex.

**Comment by kahwooi** [comment]
`this.$root.emit('refresh-badge')` works, but  `this.$root.$on('refresh-badge', () => { ` is begin called 3 times.

Here is the code, I just wanted to refresh BadgeColumn:

Fields definitions:
```
export default {
  tableFields: [
    {
      name: '__component:badge-column',
      title: '',
      dataClass: 'text-center'
    },
    {
      title: 'Id',
      name: 'Id'
    },
    {
      name: '__component:custom-actions',
      title: 'Action'
    }
  ]
}
```

badgeColumn components to have active or non active badge:
```
<template>
  <span class="circle" :class="classObject"></span>
</template>

<script>
  export default {
    name: 'badgeColumn',
    props: {
      rowData: {
        type: Object,
        required: true
      },
      rowIndex: {
        type: Number
      }
    },
    data () {
      return {
        classObject: {
          'badge-warning': this.rowData.isDisabled === true,
          'badge-primary': this.rowData.isDisabled === false
        }
      }
    },
    mounted () {
      this.$root.$on('refresh-badge', () => {
        $refs.vuetable.refresh() <= Called 3 times
      })
    }
  }
</script>
```

**Comment by ratiw** [comment]
I don't think you need to make a component to do just that, `__slot` would be a lot easier. 

And I really see no point why you need to emit an event to update its status. You can just update its underlying value, then the reactivity of Vue will take care of the rest.

**Comment by ratiw** [comment]
Please see the tutorial [here]  (https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-11#__slotname--v120)
