### ISSUE TITLE
Column ToolTip

### ISSUE THREAD

**Issue by iamgaurav** [ratiw/vuetable-2#344]
Hey

Is there any native way to have a tool-tip for the columns? Something as simple as using the title attribute for the th tags?

**Comment by ratiw** [comment]
@iamgaurav Sorry, not at the moment. You can fork the project and work on a solution. PR is always welcome if I think it's appropriate.

**Comment by iamgaurav** [comment]
If this is a requested feature then I could implement this.

**Comment by ratiw** [comment]
Please do it if you want the feature. Don't wait. It's a good learning opportunity.

If you think it is good enough to share, please send in the pull request and I'll consider it. Vuetable exists because of the same reason.

By the way, `title` is not a valid HTML5 attribute for `th` tag. You'll have to use other way.

**Comment by TurboControl** [comment]
Closed without support? I am working around this by wrapping the `title` with a div that includes the HTML tag title. e.g. `{ title: '<div title="Column tooltip">Column Name</div>' }`. I do this on the fly as I keep my definition clean with `{ title: 'Column Name', description: 'Column tooltip' }`. It would be ideal if this was natively supported. Maybe someday I can do a pull request.

**Comment by seNpAi-code** [comment]
I wanted to use tooltip on rows. I achieved this by formatting the value using `callback`. When formatting you can add bootstrap classes and attributes to add tooltip. But I still haven't achieved changing attributes dynamically according to the row value.
