### ISSUE TITLE
Using component into the render-icon

### ISSUE THREAD

**Issue by mickaelbaron** [ratiw/vuetable-2#346]
Hi,

I would like use Vue components into the render-icon. Do you know how to proceed? Any idea?

Mickael

**Comment by ratiw** [comment]
Please explain more. I don't quite understand what you want to do.

**Comment by mickaelbaron** [comment]
Hi,

**Context**
In fact i'm using Font Awesome with the version 5. There exists a component version of Font Awesome (https://github.com/FortAwesome/vue-fontawesome). To use a specific icon you can write: `<font-awesome-icon` icon="spinner" />`.

**Problem**
With the render-icon, you can specify an HTML content, but if you want specify a component content you can't. 

Maybe my need is stupid, but i'm curious to know how to solve this kind of problem. In other word how you can generate HTML content from JavaScript from component...

In the long-term, you could imagine complex components into columns and why not VueTable inside ;-)

I hope my explanation is clearer.

Mickael

**Comment by ratiw** [comment]
@mickaelbaron I don't think that is possible because in order for `<font-awesome-icon>` to work, Vue has to be able to compile it (because it is vue component). I think the only place that this can be used inside Vuetable is via the `__slot` or `__component` special field since Vue can compile and use it. I also don't know if there is any easier way to make this work outside of those mentioned context.

**Comment by mickaelbaron** [comment]
Hi, thanks for your response.

Maybe a day there will be a workaround to solve this issue.

Have a nice day

Mickael

**Comment by jeitnier** [comment]
FWIW I am interested in this too...
