### ISSUE TITLE
__sequence numeration

### ISSUE THREAD

**Issue by zaqpiotr** [ratiw/vuetable-2#363]
Hello @ratiw I'm using __sequence as it's described in wiki. What I get is:

![image](https://user-images.githubusercontent.com/2997544/35036317-435b2aa6-fb74-11e7-96bf-e45ea19654d9.png)

But I would like to have numeration from 1 not from 0 can You tell me please how to change it?

I'm using 

"vue": "^2.5.8",
"vuetable-2": "^1.7.2",

My code looks like this

```
<vuetable ref="materialvuetable"
                  :api-mode="false"
                  :data="dataGrid"
                  :fields="[
                    {
                        name: '__sequence',
                        title: '#',
                        titleClass: 'center aligned',
                        dataClass: 'right aligned'
                    },
                    ,{
                        title: 'width',
                        name: 'material.width'
                    }
                    ,{
                        title: 'height',
                        name: 'material.height'
                    }
                    ,{
                        title: 'shortcut',
                        name: 'material.shortcut'
                    }
                    ,'ilosc'
                    ,{
                        title: 'Actions',
                        name: '__component:material-and-tooling-grid-row-button',
                        titleClass: 'center aligned',
                        dataClass: 'center aligned'
                        }
                    ]"
                  @vuetable:checkbox-toggled="yyy"
                  @vuetable:cell-clicked="onCellClicked"
                  detail-row-component="material-and-tooling-grid-row-detail"
                  track-by="code"
                  detail-row-id="code"
        ></vuetable>
```

**Comment by ratiw** [comment]
`__sequence` special field requires pagination data to calculate the sequence number of the current page. Since you're using Data mode (`:api-mode="false"`), this will never work unless you also provide pagination data in the `dataGrid` object. 

See a sample project [here](https://codepen.io/ratiw/project/editor/DzmJnA).

Look at `dataManager` function in `index.js` file.

**Comment by hanxue** [comment]
Hello @ratiw , thanks for the workaround. I tried to implement `dataManager` as per the codepen, but could not make it work. 

Wouldn't it be better for vuetable's sequence to check if API mode is off, and assume the sequence 
starts from `0`?

**Comment by ratiw** [comment]
@hanxue I think it's very easy to do that using `__slot`. 

Without pagination information, `__sequence` will not be able to determine the correct sequence of each row in the data array since paging is involved. 

As in the mentioned sample, in Data mode, you can still use `__sequence` if you also return the pagination info from the `dataManager` function as demonstrated in the sample.

**Comment by zaqpiotr** [comment]
Hello @ratiw 

slot is perfect 
```

           <template slot="index" slot-scope="props">
                {{ props.rowIndex + 1}}
            </template>
```
