### ISSUE TITLE
How to ignore case when sorting in data mode

### ISSUE THREAD

**Issue by zxc23** [ratiw/vuetable-2#386]
As far as I can tell, there is no way to ignore case when sorting. Please correct me if I'm wrong.

**Comment by ratiw** [comment]
This actually has nothing to do with Vuetable because Vuetable never sorts the data by itself. It eighter relies on server side API or `data-manager` function (which you have to define by yourself) to do this job.

In the [data mode example](https://codepen.io/ratiw/project/editor/DzmJnA), I used [`lodash`](https://lodash.com/) library to perform sorting and filtering functions. You can try to research more on that. My guess is that you should be able to use `_sortBy` and define the "iteratee` function to perform sort the way you want as well.

**Comment by zxc23** [comment]
Ah, the data manager, that's it! I completely forgot that you define it there. I did it in the past and then, after a long break, it seemed like vuetable-2 was doing the sorting.

Thanks for that.
