### ISSUE TITLE
__component and events

### ISSUE THREAD

**Issue by bernhardh** [ratiw/vuetable-2#414]
I am using the special __component field just as described in https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-11

In your example, you are just logging something to the console on click. I need to create a new event and bubble it up:

```
 methods: {
      deleteRow(action, data, index) {
        this.$emit("deleteRow", this.rowData.id);
      }
    }
```

The parent of the component is the vuetable itself, so 

`<vuetable @delete-row="doSomething" ....></vuetable>`

Should work, but nothing happens (doSomething never gets triggered). What am I doing wrong?

**Comment by ratiw** [comment]
@bernhardh This is quite tricky to explain. But in the `deleteRow` method, if you use `this.$parent.$emit()` instead, it would probably work.

This is because you're listening to the custom event originated from your component inside Vuetable component. The event system in Vue 2 is not the same as in Vue 1, so it no longer buble up or down the chain as it use to be. You are suppose to use `v-on` to listen to the custom event from your component "at" your component tag. 

Let's say you have `ActionComponent` and you globally register it using `Vue.component()`. This is how you handle custom event from your component.
```html
<tr>
  <td>Something</td>
  <td>
    <action-component @deleteRow="onDeleteRow"></action-component>
  </td>
</tr>
```

Since the component used in special __component field is registered globally and vuetable does not directly declared it inside the `<vuetable>` tag, but instead uses Vue's dynamic "component". It's impossible to know which event the dynamic component will emit and therefore unable to declare `v-on` on it.

```
Vue instance
  +-- Vuetable
       +-- ActionComponent

  <vuetable>
    <component :is="ActionComponent"
       @deleteRow="onDeleteRow"
     />
  </vuetable>
```

This issue has been addressed for the next version of Vuetable, but I'm also looking into other possibility to simplify its usage.

**Comment by bernhardh** [comment]
Ok, thanks.

As an not so nice workaround, I now do the following:

```
Vue.component('action-component', ActionComponent)
ActionComponent.methods.deleteRow = function(){
	// Do something
};
```

With this, I can create a default behavior in the component itself and create custom/specific behavior in the parent component if needed.
