### ISSUE TITLE
Next and Previous

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#415]
Hello, howdy?

Im using vuetable 2 and i wanna now how can i make to get next and previous items on the table row? 

example i have expanded item 04 then i have two buttons "**Next = item 05**" and "**Previous = item 03**"

thanks for ur time

**Comment by ratiw** [comment]
Sorry, I don't understand what you mean. Do you have a drawing or picture of what you're trying to do?

**Comment by edgarscr** [comment]
@ratiw example, we can open a item to display more information, well, when i open for more information i need to add the btns Next and Previous to change and open more information

**Comment by edgarscr** [comment]
@ratiw  I try to explain my issue simpler. 
We have simple overview ticket cells with limited information. 
Example:

![image](https://user-images.githubusercontent.com/33737821/38445272-d926b5e8-39c0-11e8-83de-903c443547cd.png)

If you open a ticketcell, he shows the more detailed row in a modal. Like here:
![image](https://user-images.githubusercontent.com/33737821/38445297-eed50f8e-39c0-11e8-8f1c-4979bded41fb.png)

Now I want to add a function, that you can skip to the next detailed ticket row without closing the actually modal and opening the next modal. Can you help me?

**Comment by ratiw** [comment]
How do you pass the data into the modal?

**Comment by edgarscr** [comment]
i use two methods to make a view call:
**HTML**
`<vuetable @vuetable:cell-clicked="onCellClicked" @vuetable:row-dblclicked="onRowDBLClicked" </vuetable>`
**JS**
```
onCellClicked (data, field, event) {
			this.clickedTicket = data
			if (field.name === 'ticket_number') {
				this.$refs.viewModal.show()
			}
		}
```
**JS**
```onRowDBLClicked (data, field, event) {
			this.clickedTicket = data			
			this.$refs.viewModal.show()
},```

and i have one method to edill 

HTML
```
					<template slot="actions" scope="props">
						<div class="table-button-container row pr-2 justify-content-center">
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 p-0" style="order: 1;"><button class="btn btn-info btn-2i waves-effect waves-light" @click="editRowModal(props.rowData);"><i class="far fa-edit fa-sm material-icons"></i></button></div>
						</div>						
					</template>
```

**JS**
```
		editRowModal(rowData){
			this.clickedTicket = rowData
			this.$refs.editModal.show()
		},
```

**Comment by amensic** [comment]
Would be great if you can help us ratiw :)

**Comment by ratiw** [comment]
This depends on whether you entire data record is available inside Vuetable or not (the data array Vuetable retrieved from the API endpoint). 

If the whole data is available, you could find the previous/next item in the data array by iterating through `tableData` to match the row identity (maybe `rowData.id` or `rowData.ticket_id`). You should be able to do that via `this.$refs.vuetable.tableData`.

Since the `tableData` only holds a small number of record, it should be quite fast. However, you'll have to for the first and last item in the data array as it should also trigger loading previous/next page of data as well.

If you need to retrieve the previous/next record from the server via another API, it will be easier on the client side, but shifting the data record searching to the backend instead. The process should be more or less the same. By passing the current record id to the API for it to return the appropriate previous/next data record back for display.

**Comment by edgarscr** [comment]
@ratiw  hi good morning, howdy? i have collected all data by **API** and i have added a track by **ticket_id** but and if i press click to open modal i display the ticket_id on console but i dont know how can i extract the data but track_id.  

im using this: 

onRowDBLClicked (data, field, event) {
this.clickedTicket = data
console.log(data.ticket_id);
this.$refs.viewModal.show()
}

so i need only add next and prev with currentid more and less 1

**Comment by edgarscr** [comment]
@ratiw please?

**Comment by ratiw** [comment]
@edgarscr I'm sorry, I don't know how you implement your modal. It's impossible for me to know how it might or might not work. If you could setup an example on codepen, jsfiddle, or codesandbox, I might be able to look into it.

Anyway, why don't you create a function in your modal, e.g. `setData()` where you can pass the data into it. If you can call `this.$refs.viewModal.show()`, why not do something like this `this.$refs.viewModal.setData(data)`.
