### ISSUE TITLE
Extend the filter column properties

### ISSUE THREAD

**Issue by sylvaincaillot** [ratiw/vuetable-2#497]
I have implemented column filtering using this [example](https://codesandbox.io/s/wq540wrrnw) and it works nicely.
However, i would like to extend it further by adding a dedicated placeholder text for each column filter. So instead of a having a generic  "Search..." as here:

```
input type="text" v-model="field.filter" placeholder="search..."
              @keyup.enter="setFilter(field)"
              @blur="setFilter(field)"
            >
```

It would be nice to have a dedicated property for the placeholder text something like:

```
input type="text" v-model="field.filter" :placeholder="field.filterText"
              @keyup.enter="setFilter(field)"
              @blur="setFilter(field)"
            >
```
with the following field definitions:

```
{
                    name: 'departure',
                    title: '<i class="fa fa-pencil"></i>Departure',
                    width: "20%",                   
                    sortField: 'departure',
                    filterable: true,
                    filterText: "Search the departure city"              
                },
```

If we want to go even further, we could also have a filterField property which will be the column used in the API to process the data. It can be useful for making the API calls even more efficient. Something like:

```
{
                    name: 'departure', <--- field to display data in vuetable
                    title: '<i class="fa fa-pencil"></i>Departure',
                    width: "20%",                   
                    sortField: 'departure', <--- field to sort data in vuetable
                    filterable: true,
                    filterText: "Search the departure city",
                    filterField:"depCode" <--- field to query data in API, used in the append-params for example          
                },
```

Some thoughts...

What do you think?

S.

**Comment by ratiw** [comment]
The `RowFilter` is meant to be an example showing how you can implement it in v2.0 of Vuetable. It will not be included in Vuetable package. 

The idea is that people can create their own Vuetable specific component and share it as an npm package so that it can be pulled in (via `import`) and use with Vuetable. 

In your case, you can just put those extra parameters in the field definition and use it in your component, just as demonstrated in the 'FieldsDef.js` file. Both `togglable` and `filterable` options are not part of the standard options, but added for the use of `RowFilter` specifically.

If you have made an improvement or create a new Row component to be used with Vuetable, please let me know so that I can put the link in the repo and the others can check it out.

**Comment by sylvaincaillot** [comment]
Thank you very much @ratiw.
I haven't seen it was that flexible. Few modifications in the code and I can now target different fields for my API and add custom text in the search inputs.

Have a great week end
S.
