### ISSUE TITLE
[Bug] Promise support in dataManager broken

### ISSUE THREAD

**Issue by martixy** [ratiw/vuetable-2#511]
https://github.com/ratiw/vuetable-2/blob/7bc80be907e726fc32fe9cbd49afe7cf842547a2/src/components/Vuetable.vue#L1032-L1034

- `null` is an object
- `null` does not have a `then`

Just that is a clear failure mode of this function.

How I ran into this bug:
- I use data mode.
- Manually set the data(e.g. call `setData`).
- Return vuetable's reference to the data in the `dataManager`.

So now, when vuetable is initialized, it calls the datamanager, but data isn't set yet, you get nulls, promise check fails miserably and you get errors.

**Comment by ratiw** [comment]
@martixy Sorry, my bad. Update the code to the following should have solved it then. Did I miss anything else?

```js
  isPromiseObject (unknown) {
    return unknown !== null && typeof(unknown) === "object" && typeof(unknown.then) === "function"
  },
```

I don't know how to write a test to verify the whole Promise support, so I'm totally in a blind here. If you see anything else, please let me know. Otherwise, I'll fix it and push the beta.3 later today.

**Comment by martixy** [comment]
Yea, that should fix it. `null`s flying around shouldn't be an exceptional state otherwise, so nothing else to do.
