### ISSUE TITLE
Trying to use my custom rest api endpoint

### ISSUE THREAD

**Issue by spkuehl** [ratiw/vuetable-2#70]
I am having a hard time getting using this library with a simple custom django rest api. I am showing my inexperience, but I try plugging in my endpoint url, and I see nothing in the tableData when I inspect in a vue dev tool. I am seeing some data from my database in the tablePagination object, but nothing is populated in the table.

Can you give a demo on how to use a custom api with this library? I have been trying to tinker for a few days with no success, and I did not see a solution in the tutorial.

Thanks.

**Comment by ratiw** [comment]
@spkuehl What is your JSON data looks like?

**Comment by spkuehl** [comment]
[{"url":"http://127.0.0.1:8000/game/1/?format=json","name":"Monarch","year_published":2016,"min_players":2,"max_players":4,"pref_players":4,"min_time":1.0,"max_time":2.0,"ave_time":1.0},{"url":"http://127.0.0.1:8000/game/2/?format=json","name":"Monopoly","year_published":1921,"min_players":null,"max_players":null,"pref_players":null,"min_time":null,"max_time":null,"ave_time":null},{"url":"http://127.0.0.1:8000/game/3/?format=json","name":"Yahtzee","year_published":1931,"min_players":null,"max_players":null,"pref_players":null,"min_time":null,"max_time":null,"ave_time":null}]

**Comment by ratiw** [comment]
@spkuehl 

Vuetable expects your json data to contain pagination information and the data itself. By default, Vuetable will looks for the actual data in the `data` key in the json data, and the pagination information in `links.pagination` key.

In your case, the json data purely contain the data, so you have to set `data-path` prop to empty string (`data-path=""`). Since your json does not have pagination information as well, the pagination component will not show as well.

See the sample json data structure [here](https://github.com/ratiw/vue-table/wiki/Data-Format-(JSON)).

**Comment by spkuehl** [comment]
@ratiw: Thank you very much!
