### ISSUE TITLE
Server side datatable with vue resources

### ISSUE THREAD

**Issue by leonfather** [ratiw/vuetable-2#72]
Hello ratiw, Is this support Server side which data is passed with POST or GET parameters: query,limit,page,orderBy,ascending,byColumn and return json with calling an api with vue-resource ?

**Comment by ratiw** [comment]
@leonfather Read more info about it [here](https://github.com/ratiw/vue-table).

**Comment by leonfather** [comment]
v1.5.0 support ajax call for vue js 2 ?

**Comment by ratiw** [comment]
Both [Vuetable](https://github.com/ratiw/vue-table) and [Vuetable-2](https://github.com/ratiw/vuetable-2) is built to work with ajax call (via api endpoint) from the start.

If you are working with Vue 2.x, you can use Vuetable-2. It is almost functionally equivalent to the first version of Vuetable. I just don't have time to work on Vuetable-2 documentation yet. 

If you're new to Vuetable-2, you should first follow the tutorial project [here](https://github.com/ratiw/vuetable-2-tutorial) first to get familiar with it. Then, if you use Bootstrap or Bulma CSS, you can have a look at the code [here](https://github.com/ratiw/vuetable-2-tutorial-bootstrap) and [here](https://github.com/ratiw/vuetable-2-tutorial-bulma) respectively.

**Comment by leonfather** [comment]
thanks Ratiw for your reply.

I'll have some additional questions please:
1- is it possible to filter with keyup event instead of clicking on the search  button?
2- is it possible to search by column?
3- I may have a column that will contain only an icon, and each icon will mean either "enabled" or "disabled", how to filter the rows that contain the icon "disabled"?

Thanks in advance

**Comment by ratiw** [comment]
Please follow the tutorial first, the answer to 1 is demonstrated in there. For 2 and 3, this is not the responsibility of Vuetable, which is only a presentation part, your API endpoint should handle those functions. Whatever returns from the server side, Vuetable will display it. Vuetable just facilitates passing data/options to your API on the server side, so that it can do it works and returns the appropriate results back for display in Vuetable.

You can look at how this is done on the server side in this [sample project](https://github.com/ratiw/vuetable-sample-api-endpoint).

**Comment by leonfather** [comment]
Thank you so much
