### ISSUE TITLE
How to add class to updated row?

### ISSUE THREAD

**Issue by nizam27391** [ratiw/vuetable-2#83]
Hi. 
Thanks for this wonderful components.

But I have one question as per the title.
Let say I'm updating a row (the form isin a modal). on clicking submit, the update process will happen and I'll reload the table. But how do I find that specific row that is just updated and add a class to it. I want to apply a background color to the row so that users know which data they've updated.

Thanks in advance..

**Comment by ratiw** [comment]
@nizam27391 This is the classic "data fly-away" problem, where you make insert of the specified data row and it just went away or does not appear for you to see because of the indexing (sorting) of the table you're working on. The data you've just entered will be located at its sorting order, which may or may be in the current page of the data you're looking at.

My suggestion is that you use other mechanism (e.g. notification message) to inform your user that the data has successfully been added. Based on my experience, it is better and enough. Otherwise, you'll have to calculate where your inserted data is located (based on the current table index) and then calculate the page number where it is located, then request that specific page to be displayed. Please believe me, it doesn't worth your time to implement this.

**Comment by nizam27391** [comment]
Nice @ratiw .. Yeah i've tried to look to implement them.. Definitely not worth my time..
